### ISSUE TITLE
[Idea] add an option to set the step of series

### ISSUE THREAD

**Issue by LinuxSuRen** [guptarohit/asciigraph#14]
If I have a set of data, like 1, 200, 1000, 5000. Then the result could be very bad.

**Comment by 0x6373** [comment]
you can easily define the height of the graph with asciigraph.Height().
This is done in the asciigraph command example when you specify -h:
```
$ echo 1 200 1000 5000 |asciigraph -h 10
 5000 ┼  ╭ 
 4500 ┤  │ 
 4000 ┤  │ 
 3500 ┤  │ 
 3000 ┤  │ 
 2500 ┤  │ 
 2001 ┤  │ 
 1501 ┤  │ 
 1001 ┤ ╭╯ 
  501 ┤ │  
    1 ┼─╯  

```

**Comment by guptarohit** [comment]
Hi @LinuxSuRen, this seems to be doable already as @0x6373 mentioned in comment. Closing this issue for now, please feel free to re-open. ✨
