### ISSUE TITLE
PlotMany from command line

### ISSUE THREAD

**Issue by antoniomacri** [guptarohit/asciigraph#40]
I'd like di plot different series in the same chart, providing inputs from stdin (pipe).

Is there any way to do so?

**Comment by KarlHeitmann** [comment]
Hi @antoniomacri , I made the PR #43 to solve this issue.

**Comment by antoniomacri** [comment]
Thanks @KarlHeitmann!

I'm not using this for now, but I'll let you know if I will encounter any issue.
