### ISSUE TITLE
is it possible to generate a svg or jpg image?

### ISSUE THREAD

**Issue by 9cat** [guptarohit/asciigraph#48]
is it possible to generate a svg or jpg image file with fancy drawing by this project?

**Comment by guptarohit** [comment]
Hi, exporting svg is out of scope of this project, it only output texts.

But, if you want svg for the graph generated by this project then you can just pipe it to [goat](https://github.com/blampe/goat) (a utility to render ASCII art to SVG diagram)

e.g. `goat -i <(seq 1 72 | asciigraph -h 10 -c "plot data from stdin") -o chart.svg`
